import type { FormEvent } from 'react';
import { useCallback, useEffect, useState } from 'react';
import { Button } from '@gojet/ui';
import { adminRequest, ErrorNotice, JsonPreview, ProtectedLayout, type JsonObject, useAdminSession } from './api';

export function AdminLoginPage() {
  const [email, setEmail] = useState('admin@p17.test');
  const [password, setPassword] = useState('');
  const [totp, setTotp] = useState('');
  const [state, setState] = useState('input');
  const [error, setError] = useState('');
  async function submit(event: FormEvent) {
    event.preventDefault(); setState('submitting'); setError('');
    try {
      await adminRequest('/api/admin/auth/login', { method: 'POST', body: JSON.stringify({ email, password, totp: totp.trim() }) });
      setState('success');
    } catch (err) {
      const code = err instanceof Error ? err.message : 'internal_error'; setError(code);
      setState(code === 'totp_required' ? 'TOTP-required' : code === 'locked' ? 'locked' : code === 'rate_limited' ? 'rate-limited' : 'invalid');
    }
  }
  return <main className="p17-login" data-page="admin-login" data-state={state}><section className="p17-login-card"><p className="p17-kicker">GoJet Admin</p><h1>Administrator sign in</h1><p>Dedicated administrator authority. Workspace membership never grants this access.</p><ErrorNotice error={error} />{state === 'success' ? <div className="p17-success" role="status"><strong>Authentication complete.</strong><a href="/admin/access/administrators">Continue to Admin Access</a></div> : <form onSubmit={submit} aria-label="Administrator login"><label>Email<input type="email" autoComplete="username" required value={email} onChange={(event) => setEmail(event.target.value)} /></label><label>Password<input type="password" autoComplete="current-password" required value={password} onChange={(event) => setPassword(event.target.value)} /></label><label>TOTP code<input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" value={totp} onChange={(event) => setTotp(event.target.value)} /></label><Button type="submit" disabled={state === 'submitting'}>{state === 'submitting' ? 'Signing in…' : 'Sign in'}</Button></form>}</section></main>;
}

export function AdministratorsPage() {
  const auth = useAdminSession();
  const [items, setItems] = useState<JsonObject[]>([]); const [sessions, setSessions] = useState<JsonObject[]>([]); const [selected, setSelected] = useState<JsonObject | null>(null);
  const [error, setError] = useState(''); const [busy, setBusy] = useState(true); const [mfaSecret, setMfaSecret] = useState(''); const [mfaCode, setMfaCode] = useState(''); const [confirmSession, setConfirmSession] = useState('');
  const load = useCallback(async () => { if (!auth.session) return; setBusy(true); setError(''); try { const [admins, activeSessions] = await Promise.all([adminRequest<{ items: JsonObject[] }>('/api/admin/administrators'), adminRequest<{ items: JsonObject[] }>('/api/admin/auth/sessions')]); setItems(admins.items || []); setSessions(activeSessions.items || []); } catch (err) { setError(err instanceof Error ? err.message : 'internal_error'); } finally { setBusy(false); } }, [auth.session]);
  useEffect(() => { void load(); }, [load]);
  const state = auth.error || error ? (auth.error === 'forbidden' || error === 'forbidden' ? 'permission-denied' : 'error') : auth.busy || busy ? 'loading' : mfaSecret ? 'TOTP' : confirmSession ? 'session-revoke-confirm' : selected ? (selected.status === 'suspended' ? 'suspended' : 'detail') : items.length ? 'active' : 'empty';
  async function enroll() { if (!auth.session) return; try { const result = await adminRequest<{ secret: string }>('/api/admin/auth/totp/enroll', { method: 'POST', body: '{}' }, auth.session.csrf_token); setMfaSecret(result.secret); } catch (err) { setError(err instanceof Error ? err.message : 'internal_error'); } }
  async function confirmMFA() { if (!auth.session) return; try { await adminRequest('/api/admin/auth/totp/confirm', { method: 'POST', body: JSON.stringify({ code: mfaCode }) }, auth.session.csrf_token); setMfaSecret(''); setMfaCode(''); await auth.reload(); } catch (err) { setError(err instanceof Error ? err.message : 'internal_error'); } }
  async function revoke() { if (!auth.session || !confirmSession) return; try { await adminRequest(`/api/admin/auth/sessions/${confirmSession}/revoke`, { method: 'POST', body: JSON.stringify({ reason: 'browser accountable session revocation' }) }, auth.session.csrf_token); setConfirmSession(''); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'internal_error'); } }
  return <ProtectedLayout state={state === 'permission-denied' ? 'permission-denied' : 'normal'}><section className="p17-admin-page" data-page="admin-access" data-state={state}><header><p className="p17-kicker">Access</p><h1>Administrators</h1><p>Dedicated identities, MFA and sessions are separate from Workspace RBAC.</p></header><ErrorNotice error={auth.error || error} />{auth.session && <section className="p17-summary" aria-label="Current administrator"><strong>{auth.session.administrator.display_name}</strong><span>{auth.session.administrator.email}</span><span>{auth.session.administrator.mfa_enabled ? 'TOTP enabled' : 'TOTP not enrolled'}</span>{!auth.session.administrator.mfa_enabled && <Button type="button" onClick={() => void enroll()}>Enroll TOTP</Button>}</section>}{mfaSecret && <section className="p17-secret" role="alert" data-secret-once="true"><strong>TOTP secret — shown once</strong><code>{mfaSecret}</code><label>Six-digit code<input aria-label="TOTP confirmation code" value={mfaCode} onChange={(event) => setMfaCode(event.target.value)} /></label><Button type="button" onClick={() => void confirmMFA()}>Confirm TOTP</Button></section>}<div className="p17-grid"><section><h2>Administrator identities</h2><ul className="p17-list">{items.map((item) => <li key={String(item.id)}><button type="button" onClick={() => setSelected(item)}>{String(item.display_name || item.email)}</button><span>{String(item.status)}</span></li>)}</ul></section><section><h2>Sessions</h2><ul className="p17-list">{sessions.map((item) => <li key={String(item.id)}><code>{String(item.id).slice(0, 12)}</code><span>{String(item.status)}</span>{item.id !== auth.session?.session.id && <Button type="button" variant="ghost" onClick={() => setConfirmSession(String(item.id))}>Revoke</Button>}</li>)}</ul></section></div>{selected && <JsonPreview value={selected} />}{confirmSession && <section className="p17-confirm" role="alertdialog" aria-label="Confirm session revocation"><strong>Revoke this administrator session?</strong><Button type="button" onClick={() => void revoke()}>Confirm revoke</Button><Button type="button" variant="ghost" onClick={() => setConfirmSession('')}>Cancel</Button></section>}</section></ProtectedLayout>;
}

export function RolesPage() {
  const auth = useAdminSession(); const [roles, setRoles] = useState<JsonObject[]>([]); const [permissions, setPermissions] = useState<string[]>([]); const [selectedPermissions, setSelectedPermissions] = useState<string[]>(['platform.read']); const [name, setName] = useState('Browser operator'); const [error, setError] = useState(''); const [busy, setBusy] = useState(true);
  const load = useCallback(async () => { if (!auth.session) return; setBusy(true); try { const [r, p] = await Promise.all([adminRequest<{ items: JsonObject[] }>('/api/admin/roles'), adminRequest<{ items: string[] }>('/api/admin/permissions')]); setRoles(r.items || []); setPermissions(p.items || []); setError(''); } catch (err) { setError(err instanceof Error ? err.message : 'internal_error'); } finally { setBusy(false); } }, [auth.session]); useEffect(() => { void load(); }, [load]);
  async function create(event: FormEvent) { event.preventDefault(); if (!auth.session) return; try { await adminRequest('/api/admin/roles', { method: 'POST', body: JSON.stringify({ name, description: 'Scoped browser authority', permissions: selectedPermissions, reason: 'browser role governance' }) }, auth.session.csrf_token); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'internal_error'); } }
  const state = auth.error || error ? (error === 'conflict' ? 'permission-conflict' : auth.error === 'forbidden' || error === 'forbidden' ? 'permission-denied' : 'error') : auth.busy || busy ? 'loading' : roles.length ? 'role-list' : 'empty';
  return <ProtectedLayout state={state === 'permission-denied' ? 'permission-denied' : 'normal'}><section className="p17-admin-page" data-page="admin-roles" data-state={state}><header><p className="p17-kicker">Access</p><h1>Roles & permissions</h1><p>Permissions are explicit server-side capabilities; no universal administrator bypass exists.</p></header><ErrorNotice error={auth.error || error} /><form className="p17-form" onSubmit={create}><label>Role name<input required value={name} onChange={(event) => setName(event.target.value)} /></label><fieldset><legend>Permissions</legend>{permissions.map((permission) => <label key={permission}><input type="checkbox" checked={selectedPermissions.includes(permission)} onChange={(event) => setSelectedPermissions((current) => event.target.checked ? [...new Set([...current, permission])] : current.filter((item) => item !== permission))} />{permission}</label>)}</fieldset><Button type="submit">Create role</Button></form><p data-state-marker="in-use">Assigned roles remain durable and cannot be treated as client-side visibility.</p><ul className="p17-list">{roles.map((role) => <li key={String(role.id)}><strong>{String(role.name)}</strong><span>{Array.isArray(role.permissions) ? role.permissions.join(', ') : ''}</span></li>)}</ul></section></ProtectedLayout>;
}
