import { useCallback, useEffect, useMemo, useState } from 'react';
import { Button } from '@gojet/ui';
import { adminRequest, ErrorNotice, JsonPreview, ProtectedLayout, type JsonObject, useAdminSession } from './api';

function GovernanceListPage({ kind }: { kind: 'users' | 'workspaces' }) {
  const auth = useAdminSession(); const [items, setItems] = useState<JsonObject[]>([]); const [selected, setSelected] = useState<JsonObject | null>(null); const [confirm, setConfirm] = useState<{ id: string; action: 'suspend' | 'restore' } | null>(null); const [reason, setReason] = useState('Accountable browser governance action'); const [busy, setBusy] = useState(true); const [error, setError] = useState('');
  const base = `/api/admin/${kind}`;
  const load = useCallback(async () => { if (!auth.session) return; setBusy(true); setError(''); try { const result = await adminRequest<{ items: JsonObject[] }>(base); setItems(result.items || []); } catch (err) { setError(err instanceof Error ? err.message : 'internal_error'); } finally { setBusy(false); } }, [auth.session, base]);
  useEffect(() => { void load(); }, [load]);
  async function mutate() { if (!auth.session || !confirm) return; try { await adminRequest(`${base}/${confirm.id}/${confirm.action}`, { method: 'POST', body: JSON.stringify({ reason }) }, auth.session.csrf_token); setConfirm(null); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'internal_error'); } }
  const state = auth.error || error ? (auth.error === 'forbidden' || error === 'forbidden' ? 'permission-denied' : 'error') : auth.busy || busy ? 'loading' : confirm ? 'destructive-confirm' : selected ? 'detail' : items.length ? 'ready' : 'empty';
  return <ProtectedLayout state={state === 'permission-denied' ? 'permission-denied' : 'normal'}><section className="p17-admin-page" data-page={`admin-${kind}`} data-state={state}><header><p className="p17-kicker">Governance</p><h1>{kind === 'users' ? 'Users' : 'Workspaces'}</h1><p>Direct-route authorization is re-evaluated server-side for reads and mutations.</p></header><ErrorNotice error={auth.error || error} /><ul className="p17-list">{items.map((item) => { const id = String(item.id || item.user_id || item.workspace_id); const status = String(item.status || 'active'); return <li key={id}><button type="button" onClick={() => setSelected(item)}>{String(item.display_name || item.name || item.email || id)}</button><span>{status}</span><Button type="button" variant="ghost" onClick={() => setConfirm({ id, action: status === 'suspended' || status === 'disabled' ? 'restore' : 'suspend' })}>{status === 'suspended' || status === 'disabled' ? 'Restore' : 'Suspend'}</Button></li>; })}</ul>{selected && <JsonPreview value={selected} />}{confirm && <section className="p17-confirm" role="alertdialog" aria-label={`Confirm ${confirm.action}`}><label>Reason<input value={reason} onChange={(event) => setReason(event.target.value)} /></label><Button type="button" onClick={() => void mutate()}>Confirm {confirm.action}</Button><Button type="button" variant="ghost" onClick={() => setConfirm(null)}>Cancel</Button></section>}</section></ProtectedLayout>;
}

export function UsersPage() { return <GovernanceListPage kind="users" />; }
export function WorkspacesPage() { return <GovernanceListPage kind="workspaces" />; }

export function DomainEntitlementsPage() {
  const auth = useAdminSession(); const [items, setItems] = useState<JsonObject[]>([]); const [selected, setSelected] = useState<JsonObject | null>(null); const [filter, setFilter] = useState(''); const [busy, setBusy] = useState(true); const [error, setError] = useState(''); const [confirmAction, setConfirmAction] = useState(''); const [reason, setReason] = useState('Browser entitlement governance'); const [confirmation, setConfirmation] = useState('REVOKE'); const [impact, setImpact] = useState('disable_existing_routing');
  const load = useCallback(async () => { if (!auth.session) return; setBusy(true); setError(''); try { const result = await adminRequest<{ items: JsonObject[] }>('/api/admin/domain-entitlements'); setItems(result.items || []); } catch (err) { setError(err instanceof Error ? err.message : 'internal_error'); } finally { setBusy(false); } }, [auth.session]);
  useEffect(() => { void load(); }, [load]);
  const filtered = useMemo(() => items.filter((item) => JSON.stringify(item).toLowerCase().includes(filter.toLowerCase())), [items, filter]);
  const entitlementStatus = selected ? String(selected.entitlement?.status || selected.request?.status || selected.control?.state || 'detail') : '';
  const entitlementSource = selected ? String(selected.entitlement?.source || '') : '';
  const displayState = entitlementStatus === 'active' && entitlementSource === 'plan' ? 'active-plan' : entitlementStatus === 'active' && entitlementSource === 'manual_approval' ? 'active-manual' : entitlementStatus;
  const state = auth.error || error ? (auth.error === 'forbidden' || error === 'forbidden' ? 'permission-denied' : error === 'conflict' ? 'conflict' : 'error') : auth.busy || busy ? 'loading' : confirmAction ? 'destructive-confirm' : filter && filtered.length === 0 ? 'filtered-empty' : items.length === 0 ? 'empty' : selected ? displayState : 'queued';
  async function decide() { if (!auth.session || !selected || !confirmAction) return; const workspaceID = String(selected.workspace_id || ''); const body: JsonObject = { action: confirmAction, reason }; if (confirmAction === 'suspend') { body.effective_at = new Date().toISOString(); body.scope = 'workspace_entitlement'; } if (confirmAction === 'revoke') { body.confirmation = confirmation; body.existing_link_impact = impact; } if (confirmAction === 'restore') body.current_security_ownership_evidence = 'browser://verified-owner'; try { await adminRequest(`/api/admin/domain-entitlements/${workspaceID}/decisions`, { method: 'POST', body: JSON.stringify(body) }, auth.session.csrf_token); setConfirmAction(''); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'internal_error'); } }
  return <ProtectedLayout state={state === 'permission-denied' ? 'permission-denied' : 'normal'}><section className="p17-admin-page" data-page="admin-domain-entitlements" data-state={state}><header><p className="p17-kicker">Governance</p><h1>Domain entitlements</h1><p>P06/P13 resolution and P16 safety remain authoritative; P17 adds separate accountable controls.</p></header><ErrorNotice error={auth.error || error} /><label>Filter entitlements<input type="search" value={filter} onChange={(event) => setFilter(event.target.value)} /></label><ul className="p17-list">{filtered.map((item, index) => <li key={String(item.workspace_id || index)}><button type="button" onClick={() => setSelected(item)}>{String(item.workspace_id || 'workspace')}</button><span>{String(item.entitlement?.status || item.request?.status || item.control?.state || 'unknown')}</span></li>)}</ul>{selected && <section className="p17-detail"><JsonPreview value={selected} /><div className="p17-actions"><Button type="button" onClick={() => setConfirmAction('suspend')}>Suspend entitlement</Button><Button type="button" variant="ghost" onClick={() => setConfirmAction('revoke')}>Revoke entitlement</Button><Button type="button" variant="ghost" onClick={() => setConfirmAction('restore')}>Restore control</Button></div></section>}{confirmAction && <section className="p17-confirm" role="alertdialog" aria-label="Confirm entitlement decision"><strong>{confirmAction} domain entitlement</strong><label>Reason<input required value={reason} onChange={(event) => setReason(event.target.value)} /></label>{confirmAction === 'revoke' && <><label>Confirmation phrase<input required value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></label><label>Existing-link impact<input required value={impact} onChange={(event) => setImpact(event.target.value)} /></label></>}<Button type="button" onClick={() => void decide()}>Apply decision</Button><Button type="button" variant="ghost" onClick={() => setConfirmAction('')}>Cancel</Button></section>}</section></ProtectedLayout>;
}
