SECURITY_CASE_CONFIG = {'P15-T008': {'runner': './scripts/p15/t008_runner',
              'evidence': 'artifacts/v10/P15/security/P15-T008.json',
              'environment': 'native Go server-side session/cookie response security boundary with durable MySQL session authority and frontend storage '
                             'inspection',
              'source_paths': {'migration_000015': 'migrations/000015_authentication_oauth_account.sql',
                               'auth_store': 'internal/auth/store.go',
                               'auth_security_http': 'internal/auth/security_http.go',
                               't008_runner': 'scripts/p15/t008_runner/main.go'},
              'evidence_policy': {'raw_session_token_present': False,
                                  'raw_csrf_secret_present': False,
                                  'local_storage_auth_token_present': False,
                                  'frontend_secret_present': False},
              'forbidden_fragments': ('gst_', 'gcs_')},
 'P15-T009': {'runner': './scripts/p15/t009_runner',
              'evidence': 'artifacts/v10/P15/security/P15-T009.json',
              'environment': 'native Go session-bound HMAC CSRF authority with real Redis one-time digest replay store and durable MySQL mutation oracle',
              'requires_redis': True,
              'requires_csrf_key': True,
              'source_paths': {'migration_000015': 'migrations/000015_authentication_oauth_account.sql',
                               'auth_store': 'internal/auth/store.go',
                               'auth_security_http': 'internal/auth/security_http.go',
                               'auth_security_redis': 'internal/auth/security_redis.go',
                               't009_runner': 'scripts/p15/t009_runner/main.go'},
              'evidence_policy': {'raw_session_token_present': False,
                                  'raw_csrf_token_present': False,
                                  'raw_csrf_secret_present': False,
                                  'raw_replay_key_material_present': False},
              'forbidden_fragments': ('gcf_', 'GOJET_AUTH_CSRF_KEY_HEX', 'gst_')},
 'P15-T010': {'runner': './scripts/p15/t010_runner',
              'evidence': 'artifacts/v10/P15/security/P15-T010.json',
              'environment': 'native Go exact Origin allowlist enforced before durable unsafe mutation with session-bound CSRF and real Redis replay authority',
              'requires_redis': True,
              'requires_csrf_key': True,
              'source_paths': {'migration_000015': 'migrations/000015_authentication_oauth_account.sql',
                               'auth_security_http': 'internal/auth/security_http.go',
                               'auth_security_redis': 'internal/auth/security_redis.go',
                               't010_runner': 'scripts/p15/t010_runner/main.go'},
              'evidence_policy': {'raw_session_token_present': False,
                                  'raw_csrf_token_present': False,
                                  'raw_csrf_secret_present': False,
                                  'disallowed_origin_secret_present': False},
              'forbidden_fragments': ('gcf_', 'GOJET_AUTH_CSRF_KEY_HEX', 'gst_')},
 'P15-T011': {'runner': './scripts/p15/t011_runner',
              'evidence': 'artifacts/v10/P15/security/P15-T011.json',
              'environment': 'native Go P15 auth Turnstile guard delegating to inherited P14 server verifier with real Redis digest replay authority and '
                             'durable MySQL mutation oracle',
              'requires_redis': True,
              'source_paths': {'auth_turnstile': 'internal/auth/turnstile.go',
                               'auth_security_redis': 'internal/auth/security_redis.go',
                               'p14_turnstile_boundary': 'internal/support/turnstile.go',
                               'p14_turnstile_deterministic': 'internal/support/turnstile_deterministic.go',
                               't011_runner': 'scripts/p15/t011_runner/main.go'},
              'evidence_policy': {'raw_turnstile_token_present': False,
                                  'raw_turnstile_replay_key_present': False,
                                  'production_bypass_present': False,
                                  'raw_session_token_present': False},
              'forbidden_fragments': ('p15-t011-valid-', 'p15-t011-invalid', 'p15-t011-provider-failure')},
 'P15-T012': {'runner': './scripts/p15/t012_runner',
              'evidence': 'artifacts/v10/P15/security/P15-T012.json',
              'environment': 'native Go Redis-backed dual identity/IP auth abuse limiter across register/login/login-code/recovery surfaces with safe hashed '
                             'keys',
              'requires_redis': True,
              'source_paths': {'auth_security_redis': 'internal/auth/security_redis.go', 't012_runner': 'scripts/p15/t012_runner/main.go'},
              'evidence_policy': {'raw_identity_present': False,
                                  'raw_remote_ip_present': False,
                                  'raw_rate_limit_key_material_present': False,
                                  'account_existence_signal_present': False},
              'forbidden_fragments': ('203.0.113.', '198.51.100.', '@example.test', 'p15-t012-')}}
