ACCOUNT_OAUTH_CASE_CONFIG = {
    "P15-T013": {
        "runner": "./scripts/p15/t013_runner",
        "evidence": "artifacts/v10/P15/api/P15-T013.json",
        "environment": "native Go P15 account session service with durable MySQL ownership/revocation and real Redis-backed request authority",
        "requires_redis": True,
        "requires_csrf_key": True,
        "source_paths": {
            "auth_account": "internal/auth/account.go",
            "auth_store": "internal/auth/store.go",
            "auth_mutation_authority": "internal/auth/mutation_authority.go",
            "auth_security_http": "internal/auth/security_http.go",
            "auth_security_redis": "internal/auth/security_redis.go",
            "runner_util": "scripts/p15/runnerutil/util.go",
            "t013_runner": "scripts/p15/t013_runner/main.go",
        },
        "evidence_policy": {
            "raw_session_token_present": False,
            "raw_csrf_token_present": False,
            "raw_csrf_key_present": False,
            "foreign_user_pii_present": False,
        },
        "forbidden_fragments": ("gst_", "gcs_", "gcf_", "GOJET_AUTH_CSRF_KEY_HEX"),
    },
    "P15-T014": {
        "runner": "./scripts/p15/t014_runner",
        "evidence": "artifacts/v10/P15/api/P15-T014.json",
        "environment": "native Go P15 profile/password account service with durable MySQL and real Redis-backed CSRF/Origin mutation authority",
        "requires_grant_key": True,
        "requires_redis": True,
        "requires_csrf_key": True,
        "source_paths": {
            "auth_account": "internal/auth/account.go",
            "auth_password": "internal/auth/password.go",
            "auth_login": "internal/auth/login.go",
            "auth_mutation_authority": "internal/auth/mutation_authority.go",
            "auth_security_http": "internal/auth/security_http.go",
            "runner_util": "scripts/p15/runnerutil/util.go",
            "t014_runner": "scripts/p15/t014_runner/main.go",
        },
        "evidence_policy": {
            "raw_old_password_present": False,
            "raw_new_password_present": False,
            "raw_session_token_present": False,
            "raw_csrf_token_present": False,
            "raw_grant_key_present": False,
        },
        "forbidden_fragments": ("P15-T014 Old Password!", "P15-T014 New Password!", "gst_", "gcs_", "gcf_", "GOJET_AUTH_GRANT_KEY_HEX", "GOJET_AUTH_CSRF_KEY_HEX"),
    },
    "P15-T015": {
        "runner": "./scripts/p15/t015_runner",
        "evidence": "artifacts/v10/P15/oauth/P15-T015.json",
        "environment": "native Go P15 connected-account bind/unbind lifecycle with durable MySQL state/identity authority, encrypted provider config and real Redis request authority",
        "requires_redis": True,
        "requires_csrf_key": True,
        "requires_oauth_key": True,
        "source_paths": {
            "migration_000018": "migrations/000018_auth_oauth_runtime.sql",
            "auth_oauth_types": "internal/auth/oauth_types.go",
            "auth_oauth_provider": "internal/auth/oauth_provider.go",
            "auth_oauth_flow": "internal/auth/oauth_flow.go",
            "auth_oauth_connected": "internal/auth/oauth_connected.go",
            "auth_oauth_crypto": "internal/auth/oauth_crypto.go",
            "auth_mutation_authority": "internal/auth/mutation_authority.go",
            "auth_account": "internal/auth/account.go",
            "runner_util": "scripts/p15/runnerutil/util.go",
            "t015_runner": "scripts/p15/t015_runner/main.go",
        },
        "evidence_policy": {
            "raw_provider_subject_present": False,
            "raw_oauth_state_present": False,
            "raw_pkce_verifier_present": False,
            "raw_provider_client_secret_present": False,
            "raw_session_token_present": False,
        },
        "forbidden_fragments": ("p15-t015-provider-subject", "p15-t015-client-secret", "gos_", "gpk_", "gst_", "GOJET_OAUTH_KEY_HEX"),
    },
    "P15-T016": {
        "runner": "./scripts/p15/t016_runner",
        "evidence": "artifacts/v10/P15/oauth/P15-T016.json",
        "environment": "native Go P15 exact six-provider registry and settings.manage-consumed encrypted configuration authority on durable MySQL",
        "requires_redis": True,
        "requires_csrf_key": True,
        "requires_oauth_key": True,
        "source_paths": {
            "migration_000015": "migrations/000015_authentication_oauth_account.sql",
            "migration_000018": "migrations/000018_auth_oauth_runtime.sql",
            "auth_model": "internal/auth/model.go",
            "auth_oauth_types": "internal/auth/oauth_types.go",
            "auth_oauth_provider": "internal/auth/oauth_provider.go",
            "auth_oauth_flow": "internal/auth/oauth_flow.go",
            "auth_oauth_connected": "internal/auth/oauth_connected.go",
            "auth_oauth_crypto": "internal/auth/oauth_crypto.go",
            "auth_mutation_authority": "internal/auth/mutation_authority.go",
            "runner_util": "scripts/p15/runnerutil/util.go",
            "t016_runner": "scripts/p15/t016_runner/main.go",
        },
        "evidence_policy": {
            "raw_provider_client_secret_present": False,
            "raw_oauth_encryption_key_present": False,
            "permission_lifecycle_claim_present": False,
        },
        "forbidden_fragments": ("p15-t016-client-secret", "p15-t016-denied-secret", "GOJET_OAUTH_KEY_HEX"),
    },
    "P15-T017": {
        "runner": "./scripts/p15/t017_runner",
        "evidence": "artifacts/v10/P15/oauth/P15-T017.json",
        "environment": "native Go P15 OAuth start lifecycle with durable MySQL hash-only state, encrypted PKCE and reviewed server redirect configuration",
        "requires_redis": True,
        "requires_csrf_key": True,
        "requires_oauth_key": True,
        "source_paths": {
            "migration_000015": "migrations/000015_authentication_oauth_account.sql",
            "migration_000018": "migrations/000018_auth_oauth_runtime.sql",
            "auth_oauth_types": "internal/auth/oauth_types.go",
            "auth_oauth_provider": "internal/auth/oauth_provider.go",
            "auth_oauth_flow": "internal/auth/oauth_flow.go",
            "auth_oauth_connected": "internal/auth/oauth_connected.go",
            "auth_oauth_crypto": "internal/auth/oauth_crypto.go",
            "auth_opaque": "internal/auth/opaque.go",
            "runner_util": "scripts/p15/runnerutil/util.go",
            "t017_runner": "scripts/p15/t017_runner/main.go",
        },
        "evidence_policy": {
            "raw_oauth_state_present": False,
            "raw_pkce_verifier_present": False,
            "raw_provider_client_secret_present": False,
            "raw_oauth_key_present": False,
        },
        "forbidden_fragments": ("gos_", "gpk_", "p15-t017-client-secret", "GOJET_OAUTH_KEY_HEX"),
    },
    "P15-T018": {
        "runner": "./scripts/p15/t018_runner",
        "evidence": "artifacts/v10/P15/oauth/P15-T018.json",
        "environment": "native Go P15 OAuth callback with durable MySQL one-time state, encrypted PKCE/client secret and deterministic local provider exchange adapter",
        "requires_redis": True,
        "requires_csrf_key": True,
        "requires_oauth_key": True,
        "source_paths": {
            "migration_000015": "migrations/000015_authentication_oauth_account.sql",
            "migration_000018": "migrations/000018_auth_oauth_runtime.sql",
            "auth_oauth_types": "internal/auth/oauth_types.go",
            "auth_oauth_provider": "internal/auth/oauth_provider.go",
            "auth_oauth_flow": "internal/auth/oauth_flow.go",
            "auth_oauth_connected": "internal/auth/oauth_connected.go",
            "auth_oauth_crypto": "internal/auth/oauth_crypto.go",
            "runner_util": "scripts/p15/runnerutil/util.go",
            "t018_runner": "scripts/p15/t018_runner/main.go",
        },
        "evidence_policy": {
            "raw_oauth_state_present": False,
            "raw_pkce_verifier_present": False,
            "raw_provider_code_present": False,
            "raw_provider_client_secret_present": False,
            "raw_provider_subject_present": False,
        },
        "forbidden_fragments": ("gos_", "gpk_", "p15-t018-good-code", "p15-t018-client-secret", "p15-t018-subject", "GOJET_OAUTH_KEY_HEX"),
    },
}
