CORE_CASE_CONFIG = {'P15-T001': {'runner': './scripts/p15/t001_runner',
              'evidence': 'artifacts/v10/P15/api/P15-T001.json',
              'environment': 'native Go internal/auth Store against durable MySQL',
              'source_paths': {'migration_000015': 'migrations/000015_authentication_oauth_account.sql',
                               'auth_store': 'internal/auth/store.go',
                               'auth_model': 'internal/auth/model.go',
                               'auth_opaque': 'internal/auth/opaque.go',
                               't001_runner': 'scripts/p15/t001_runner/main.go'},
              'evidence_policy': {'raw_password_present': False,
                                  'raw_session_token_present': False,
                                  'raw_csrf_secret_present': False,
                                  'raw_oauth_subject_present': False,
                                  'raw_oauth_token_present': False},
              'forbidden_fragments': ('gst_', 'gcs_', 'p15-t001-provider-subject-', 'p15-t001-schema-fixture:')},
 'P15-T002': {'runner': './scripts/p15/t002_runner',
              'evidence': 'artifacts/v10/P15/api/P15-T002.json',
              'environment': 'native Go P15 registration service with durable MySQL and inherited P14 mail queue/template authority',
              'requires_grant_key': True,
              'source_paths': {'migration_000015': 'migrations/000015_authentication_oauth_account.sql',
                               'migration_000016': 'migrations/000016_auth_verification_mail.sql',
                               'auth_registration': 'internal/auth/registration.go',
                               'secure_token_derivation': 'internal/securetoken/grant.go',
                               'p14_mail_enqueue_boundary': 'internal/support/mail_enqueue.go',
                               'p14_mail_core': 'internal/support/mail.go',
                               'p14_mail_store': 'internal/support/mail_store.go',
                               't002_runner': 'scripts/p15/t002_runner/main.go'},
              'evidence_policy': {'raw_password_present': False,
                                  'raw_verification_code_present': False,
                                  'raw_grant_key_present': False,
                                  'raw_session_token_present': False,
                                  'raw_oauth_token_present': False},
              'forbidden_fragments': ('gvc_', 'p15-t002-schema-secret')},
 'P15-T003': {'runner': './scripts/p15/t003_runner',
              'evidence': 'artifacts/v10/P15/security/P15-T003.json',
              'environment': 'native Go P15 email-verification consumption service with durable MySQL one-time grant authority',
              'requires_grant_key': True,
              'source_paths': {'migration_000015': 'migrations/000015_authentication_oauth_account.sql',
                               'migration_000016': 'migrations/000016_auth_verification_mail.sql',
                               'auth_registration': 'internal/auth/registration.go',
                               'auth_verification': 'internal/auth/verification.go',
                               'auth_store': 'internal/auth/store.go',
                               'secure_token_derivation': 'internal/securetoken/grant.go',
                               't003_runner': 'scripts/p15/t003_runner/main.go'},
              'evidence_policy': {'raw_password_present': False,
                                  'raw_verification_code_present': False,
                                  'raw_grant_key_present': False,
                                  'raw_session_token_present': False,
                                  'raw_oauth_token_present': False},
              'forbidden_fragments': ('gvc_', 'GOJET_AUTH_GRANT_KEY_HEX')},
 'P15-T004': {'runner': './scripts/p15/t004_runner',
              'evidence': 'artifacts/v10/P15/api/P15-T004.json',
              'environment': 'native Go P15 password credential/login services with durable MySQL account/session authority',
              'requires_grant_key': True,
              'source_paths': {'migration_000015': 'migrations/000015_authentication_oauth_account.sql',
                               'migration_000016': 'migrations/000016_auth_verification_mail.sql',
                               'auth_password': 'internal/auth/password.go',
                               'auth_login': 'internal/auth/login.go',
                               'auth_registration': 'internal/auth/registration.go',
                               'auth_verification': 'internal/auth/verification.go',
                               'auth_store': 'internal/auth/store.go',
                               'auth_opaque': 'internal/auth/opaque.go',
                               't004_runner': 'scripts/p15/t004_runner/main.go'},
              'evidence_policy': {'raw_password_present': False,
                                  'raw_verification_code_present': False,
                                  'raw_session_token_present': False,
                                  'raw_csrf_secret_present': False,
                                  'raw_grant_key_present': False,
                                  'client_asserted_identity_present': False},
              'forbidden_fragments': ('P15-T004 Active Password!',
                                      'P15-T004 Pending Password!',
                                      'P15-T004 Locked Password!',
                                      'gst_',
                                      'gcs_',
                                      'GOJET_AUTH_GRANT_KEY_HEX')},
 'P15-T005': {'runner': './scripts/p15/t005_runner',
              'evidence': 'artifacts/v10/P15/security/P15-T005.json',
              'environment': 'native Go P15 login-email-code service with durable MySQL one-time grant/session authority and inherited P14 mail queue/template '
                             'authority',
              'requires_grant_key': True,
              'source_paths': {'migration_000015': 'migrations/000015_authentication_oauth_account.sql',
                               'migration_000016': 'migrations/000016_auth_verification_mail.sql',
                               'migration_000017': 'migrations/000017_auth_login_recovery_mail.sql',
                               'auth_email_code': 'internal/auth/email_code.go',
                               'auth_registration': 'internal/auth/registration.go',
                               'auth_verification': 'internal/auth/verification.go',
                               'secure_token_derivation': 'internal/securetoken/grant.go',
                               'p14_mail_enqueue_boundary': 'internal/support/mail_enqueue.go',
                               't005_runner': 'scripts/p15/t005_runner/main.go'},
              'evidence_policy': {'raw_login_code_present': False,
                                  'raw_grant_key_present': False,
                                  'raw_session_token_present': False,
                                  'raw_csrf_secret_present': False,
                                  'raw_oauth_token_present': False},
              'forbidden_fragments': ('glc_', 'gst_', 'gcs_', 'GOJET_AUTH_GRANT_KEY_HEX')},
 'P15-T006': {'runner': './scripts/p15/t006_runner',
              'evidence': 'artifacts/v10/P15/security/P15-T006.json',
              'environment': 'native Go P15 password-recovery request service with neutral public result, durable MySQL grant authority and inherited P14 mail '
                             'queue/template authority',
              'requires_grant_key': True,
              'source_paths': {'migration_000015': 'migrations/000015_authentication_oauth_account.sql',
                               'migration_000017': 'migrations/000017_auth_login_recovery_mail.sql',
                               'auth_recovery': 'internal/auth/recovery.go',
                               'auth_password': 'internal/auth/password.go',
                               'secure_token_derivation': 'internal/securetoken/grant.go',
                               'p14_mail_enqueue_boundary': 'internal/support/mail_enqueue.go',
                               't006_runner': 'scripts/p15/t006_runner/main.go'},
              'evidence_policy': {'raw_password_present': False,
                                  'raw_reset_token_present': False,
                                  'raw_grant_key_present': False,
                                  'account_existence_result_present': False,
                                  'raw_session_token_present': False},
              'forbidden_fragments': ('grp_', 'P15-T006 Existing Password!', 'GOJET_AUTH_GRANT_KEY_HEX')},
 'P15-T007': {'runner': './scripts/p15/t007_runner',
              'evidence': 'artifacts/v10/P15/security/P15-T007.json',
              'environment': 'native Go P15 password-reset consumption service with durable MySQL one-time grant, credential and session-revocation authority',
              'requires_grant_key': True,
              'source_paths': {'migration_000015': 'migrations/000015_authentication_oauth_account.sql',
                               'migration_000017': 'migrations/000017_auth_login_recovery_mail.sql',
                               'auth_recovery': 'internal/auth/recovery.go',
                               'auth_password': 'internal/auth/password.go',
                               'auth_login': 'internal/auth/login.go',
                               'auth_store': 'internal/auth/store.go',
                               'secure_token_derivation': 'internal/securetoken/grant.go',
                               't007_runner': 'scripts/p15/t007_runner/main.go'},
              'evidence_policy': {'raw_old_password_present': False,
                                  'raw_new_password_present': False,
                                  'raw_reset_token_present': False,
                                  'raw_grant_key_present': False,
                                  'raw_session_token_present': False},
              'forbidden_fragments': ('P15-T007 Old Password!',
                                      'P15-T007 New Password!',
                                      'P15-T007 Replay Password!',
                                      'P15-T007 Must Not Apply!',
                                      'grp_',
                                      'gst_',
                                      'GOJET_AUTH_GRANT_KEY_HEX')}}
