HANDOFF_MAIL_AUDIT_CASE_CONFIG = {
    "P15-T019": {
        "runner": "./scripts/p15/t019_runner",
        "evidence": "artifacts/v10/P15/oauth/P15-T019.json",
        "environment": "native Go P15 callback-to-browser handoff lifecycle with durable MySQL hash-only authority and deterministic local OAuth exchange",
        "requires_redis": True,
        "requires_csrf_key": True,
        "requires_oauth_key": True,
        "source_paths": {
            "migration_000019": "migrations/000019_auth_social_handoff.sql",
            "auth_oauth_handoff": "internal/auth/oauth_handoff.go",
            "auth_oauth_flow": "internal/auth/oauth_flow.go",
            "auth_oauth_provider": "internal/auth/oauth_provider.go",
            "runner_util": "scripts/p15/runnerutil/util.go",
            "batch_runner": "scripts/p15/handoffbatch/runner.go",
            "case_runner": "scripts/p15/handoffbatch/case_t019.go",
            "t019_runner": "scripts/p15/t019_runner/main.go",
        },
        "evidence_policy": {
            "raw_browser_handoff_present": False,
            "raw_social_handoff_present": False,
            "raw_provider_subject_present": False,
            "raw_provider_client_secret_present": False,
        },
        "forbidden_fragments": ("goh_", "gsr_", "p15-t019-subject", "p15-t019-client-secret", "GOJET_OAUTH_KEY_HEX"),
    },
    "P15-T020": {
        "runner": "./scripts/p15/t020_runner",
        "evidence": "artifacts/v10/P15/oauth/P15-T020.json",
        "environment": "native Go P15 social registration continuation with durable MySQL handoff/grant state, inherited P14 mail enqueue and one-time email verification",
        "requires_grant_key": True,
        "requires_redis": True,
        "requires_csrf_key": True,
        "requires_oauth_key": True,
        "source_paths": {
            "migration_000019": "migrations/000019_auth_social_handoff.sql",
            "auth_oauth_handoff": "internal/auth/oauth_handoff.go",
            "auth_social_registration": "internal/auth/social_registration.go",
            "auth_mail_queue": "internal/auth/auth_mail_queue.go",
            "runner_util": "scripts/p15/runnerutil/util.go",
            "batch_runner": "scripts/p15/handoffbatch/runner.go",
            "case_runner": "scripts/p15/handoffbatch/case_t020.go",
            "t020_runner": "scripts/p15/t020_runner/main.go",
        },
        "evidence_policy": {
            "raw_social_handoff_present": False,
            "raw_social_verification_code_present": False,
            "raw_provider_subject_present": False,
            "raw_grant_key_present": False,
        },
        "forbidden_fragments": ("gsr_", "gsv_", "p15-t020-subject", "GOJET_AUTH_GRANT_KEY_HEX"),
    },
    "P15-T021": {
        "runner": "./scripts/p15/t021_runner",
        "evidence": "artifacts/v10/P15/oauth/P15-T021.json",
        "environment": "native Go P15 OAuth identity ownership and takeover-denial lifecycle on durable MySQL with one-time browser authority",
        "requires_grant_key": True,
        "requires_redis": True,
        "requires_csrf_key": True,
        "requires_oauth_key": True,
        "source_paths": {
            "migration_000019": "migrations/000019_auth_social_handoff.sql",
            "auth_oauth_handoff": "internal/auth/oauth_handoff.go",
            "auth_social_registration": "internal/auth/social_registration.go",
            "auth_oauth_connected": "internal/auth/oauth_connected.go",
            "runner_util": "scripts/p15/runnerutil/util.go",
            "batch_runner": "scripts/p15/handoffbatch/runner.go",
            "case_runner": "scripts/p15/handoffbatch/case_t021.go",
            "t021_runner": "scripts/p15/t021_runner/main.go",
        },
        "evidence_policy": {
            "raw_browser_handoff_present": False,
            "raw_provider_subject_present": False,
            "raw_provider_client_secret_present": False,
            "foreign_session_token_present": False,
        },
        "forbidden_fragments": ("goh_", "p15-t021-subject", "p15-t021-client-secret", "gst_", "GOJET_OAUTH_KEY_HEX"),
    },
    "P15-T022": {
        "runner": "./scripts/p15/t022_runner",
        "evidence": "artifacts/v10/P15/mail/P15-T022.json",
        "environment": "native Go P15 verification/login-code/recovery grants delivered through signed P14 durable MySQL mail queue semantics",
        "requires_grant_key": True,
        "source_paths": {
            "auth_registration": "internal/auth/registration.go",
            "auth_email_code": "internal/auth/email_code.go",
            "auth_recovery": "internal/auth/recovery.go",
            "auth_mail_queue": "internal/auth/auth_mail_queue.go",
            "support_mail": "internal/support/mail.go",
            "support_mail_store": "internal/support/mail_store.go",
            "runner_util": "scripts/p15/runnerutil/util.go",
            "batch_runner": "scripts/p15/handoffbatch/runner.go",
            "case_runner": "scripts/p15/handoffbatch/case_t022.go",
            "t022_runner": "scripts/p15/t022_runner/main.go",
        },
        "evidence_policy": {
            "raw_verification_code_present": False,
            "raw_login_code_present": False,
            "raw_reset_token_present": False,
            "raw_mail_claim_token_present": False,
            "raw_grant_key_present": False,
        },
        "forbidden_fragments": ("gvc_", "glc_", "grp_", "p15-t022-mail-claim", "GOJET_AUTH_GRANT_KEY_HEX"),
    },
    "P15-T023": {
        "runner": "./scripts/p15/t023_runner",
        "evidence": "artifacts/v10/P15/security/P15-T023.json",
        "environment": "native Go P15 private Auth response policy and secure session-cookie contract with MySQL-backed integration harness",
        "source_paths": {
            "auth_security_http": "internal/auth/security_http.go",
            "batch_runner": "scripts/p15/handoffbatch/runner.go",
            "case_runner": "scripts/p15/handoffbatch/case_t023.go",
            "t023_runner": "scripts/p15/t023_runner/main.go",
        },
        "evidence_policy": {
            "raw_session_cookie_present": False,
            "cacheable_auth_response_claim": False,
            "indexable_auth_response_claim": False,
        },
        "forbidden_fragments": ("p15-t023-session-token",),
    },
    "P15-T027": {
        "runner": "./scripts/p15/t027_runner",
        "evidence": "artifacts/v10/P15/audit/P15-T027.json",
        "environment": "native Go P15 correlated audit ledger safety over real MySQL mutations with raw identity/session/OAuth/grant material excluded",
        "requires_grant_key": True,
        "requires_redis": True,
        "requires_csrf_key": True,
        "requires_oauth_key": True,
        "source_paths": {
            "auth_registration": "internal/auth/registration.go",
            "auth_oauth_flow": "internal/auth/oauth_flow.go",
            "auth_oauth_handoff": "internal/auth/oauth_handoff.go",
            "auth_social_registration": "internal/auth/social_registration.go",
            "auth_account": "internal/auth/account.go",
            "runner_util": "scripts/p15/runnerutil/util.go",
            "batch_runner": "scripts/p15/handoffbatch/runner.go",
            "case_runner": "scripts/p15/handoffbatch/case_t027.go",
            "t027_runner": "scripts/p15/t027_runner/main.go",
        },
        "evidence_policy": {
            "raw_password_present": False,
            "raw_oauth_state_present": False,
            "raw_pkce_present": False,
            "raw_provider_code_present": False,
            "raw_provider_secret_present": False,
            "raw_handoff_present": False,
            "raw_session_token_present": False,
            "unnecessary_pii_present": False,
        },
        "forbidden_fragments": ("P15-T027 Password!", "gos_", "gpk_", "goh_", "gsr_", "p15-t027-oauth-provider-code", "p15-t027-client-secret", "p15-t027-subject", "gst_"),
    },
}
