"""Pinned P16 assertions reviewed for the frozen T029 oracle."""
REQUIRED = {'domain/P16-T015.json': {'checks': ['allow_decision_is_durable_and_projected',
                                     'both_correlations_are_persisted',
                                     'domain_risk_audit_is_durable',
                                     'entitlement_snapshot_is_independent',
                                     'only_risk_allow_satisfies_inherited_readiness_axis',
                                     'ownership_dns_https_routing_axes_unchanged',
                                     'p06_risk_revalidation_seam_is_used',
                                     'provider_observations_are_durable',
                                     'review_decision_is_durable_and_non_allow'],
                          'counts': {'domain_risk_audit_events': 4,
                                     'domain_risk_evaluations': 2,
                                     'domains_with_other_axes_intact': 2,
                                     'p06_risk_revalidation_records': 4,
                                     'provider_observations': 2}},
 'risk/P16-T008.json': {'checks': ['allow_projection_policy_version_is_exact',
                                   'allow_projection_ttl_is_bounded',
                                   'current_fingerprint_has_no_stale_projection',
                                   'durable_authority_remains_mysql_source',
                                   'durable_current_allow_projects_exact_key',
                                   'durable_review_overwrites_prior_runtime_allow',
                                   'old_fingerprint_projection_is_not_current_authority',
                                   'policy_mismatch_cannot_replace_projection',
                                   'projection_candidate_query_excludes_stale_fingerprint',
                                   'target_mutation_invalidates_old_durable_authority'],
                        'counts': {'current_projection_candidates': 0,
                                   'durable_decisions': 2,
                                   'redis_keys': 1}},
 'security/P16-T010.json': {'checks': ['all_three_frozen_target_classes_are_covered',
                                       'allow_enforcement_releases_both_hosts_only_after_approval',
                                       'custom_host_used_real_independent_p06_axes',
                                       'every_selected_target_on_both_hosts_is_fingerprint_member',
                                       'official_custom_exact_fingerprint_parity',
                                       'primary_routing_ab_selection_is_valid_on_both_hosts',
                                       'review_fails_closed_identically_on_both_hosts'],
                            'counts': {'native_allow_redirects': 6,
                                       'official_custom_pairs': 3,
                                       'ready_custom_domains': 1}},
 'security/P16-T011.json': {'checks': ['duplicate_target_dedup_and_reorder_preserve_fingerprint',
                                       'mutation_safety_response_discloses_no_old_or_new_target',
                                       'old_allow_key_cannot_authorize_new_fingerprint',
                                       'pre_mutation_exact_allow_redirects',
                                       'reachable_target_mutation_changes_fingerprint',
                                       'semantically_equivalent_change_keeps_exact_allow_authority',
                                       'stable_redirect_remains_within_exact_target_set'],
                            'counts': {'new_projection_keys_without_rescan': 0,
                                       'old_projection_keys_preserved_for_non_authoritative_history': 1,
                                       'stable_projection_keys': 1}}}
