"""Bind independent representative WCAG review to the exact native packet.

No review is generated by this module. Missing, incomplete or stale review
rejects formal admission even when native automated diagnostics pass.
"""
import json
import os
from pathlib import Path
from t028_sources import require, digest

CRITERIA = tuple('''1.1.1 1.2.1 1.2.2 1.2.3 1.2.4 1.2.5
1.3.1 1.3.2 1.3.3 1.3.4 1.3.5
1.4.1 1.4.2 1.4.3 1.4.4 1.4.5 1.4.10 1.4.11 1.4.12 1.4.13
2.1.1 2.1.2 2.1.4 2.2.1 2.2.2 2.3.1
2.4.1 2.4.2 2.4.3 2.4.4 2.4.5 2.4.6 2.4.7 2.4.11
2.5.1 2.5.2 2.5.3 2.5.4 2.5.7 2.5.8
3.1.1 3.1.2 3.2.1 3.2.2 3.2.3 3.2.4 3.2.6
3.3.1 3.3.2 3.3.3 3.3.4 3.3.7 3.3.8 4.1.2 4.1.3'''.split())
BEGIN = '<!-- P20-T035-REVIEW:BEGIN -->'
END = '<!-- P20-T035-REVIEW:END -->'


def load_review():
    import sys
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    from ci.actions import github_json
    require(os.environ.get('GITHUB_REPOSITORY') == 'Techshrr/GoJet', 'untrusted review repository')
    headers = {'Accept': 'application/vnd.github+json'}
    if os.environ.get('GH_TOKEN'):
        headers['Authorization'] = 'Bearer ' + os.environ['GH_TOKEN']
    issue = github_json('https://api.github.com/repos/Techshrr/GoJet/issues/188', headers)
    body = issue.get('body') or ''
    require(issue.get('number') == 188 and body.count(BEGIN) == body.count(END) == 1,
            'independent T035 review absent/ambiguous')
    return json.loads(body.split(BEGIN)[1].split(END)[0].strip())


def validate_review(root, head, details, review):
    require(isinstance(review, dict), 'invalid review record')
    require(review.get('case') == 'P20-T035' and review.get('implementation_commit') == head
            and review.get('status') == 'PASS' and review.get('role') == 'Accessibility Reviewer'
            and isinstance(review.get('reviewer'), str) and bool(review['reviewer'].strip())
            and review.get('findings') == [], 'unsigned/incomplete/failed review')
    require(review.get('collection_sha256') == details['collection_sha256'], 'stale review packet')
    source = root / 'artifacts/v10/P20/runtime/t035-sources'
    manifest = json.loads((source / 'collection.json').read_bytes())
    captures = {path: row['sha256'] for path, row in manifest['files'].items() if path.endswith('.png')
                and not path.startswith('prerequisite/')}
    require(len(captures) == 109 and review.get('captures') == captures, 'incomplete/stale capture review')
    sources = review.get('source_files')
    require(isinstance(sources, dict) and bool(sources), 'source review absent')
    for path, expected in sources.items():
        relative = Path(path)
        require(bool(relative.parts) and not relative.is_absolute() and '..' not in relative.parts
                and relative.parts[0] in ('frontend', 'internal', 'services'), 'unsafe review source')
        require(digest((root / relative).read_bytes()) == expected, 'stale reviewed source')
    rows = review.get('criteria')
    require(isinstance(rows, dict) and set(rows) == set(CRITERIA), 'incomplete WCAG 2.2 A/AA review')
    for cid, row in rows.items():
        require(isinstance(row, dict) and row.get('disposition') in ('PASS', 'NOT_APPLICABLE')
                and isinstance(row.get('reason'), str) and bool(row['reason'].strip())
                and isinstance(row.get('evidence'), list) and bool(row['evidence'])
                and all(path in captures or path in sources or path in manifest['files'] for path in row['evidence']),
                'unsupported manual criterion: ' + cid)
    require(all(rows[cid]['disposition'] == 'PASS' for cid in ('1.4.4','1.4.10','1.4.12','2.1.1','2.4.7','3.3.4','3.3.8','4.1.2','4.1.3')),
            'applicable representative obligations cannot be waived')
    require(review.get('screen_reader_sample_scope_acknowledged') is True,
            'screen-reader sample overstated as audible/full-page certification')
    return {'reviewer': review['reviewer'], 'role': review['role'], 'criteria': len(rows),
            'captures': len(captures), 'source_files': len(sources), 'review_sha256': digest(json.dumps(review, sort_keys=True).encode()),
            'authority': 'repository tracker #188; exact head, packet, captures and source digests'}
